NethServer/nethserver-mail

common/etc/e-smith/templates/etc/postfix/main.cf/00template_vars, common/etc/e-smith/templates/etc/postfix/main.cf/70smtpd_milters, common/etc/e-smith/templates/etc/postfix/master.cf/00template_vars, filter/etc/e-smith/templates/etc/postfix/main.cf/01template_vars_rspamd, filter/etc/e-smith/templates/etc/postfix/main.cf/70smtpd_milters
Disable DKIM milter on port 25 to avoid signatures on messages from untrusted clients.
=> DKIM milter on submission ports only

createlinks-filter
Event trusted-networks-modify is used to expand the local_addrs  and to reload rspamd
=> Expand local IP following trusted-networks-modify

filter/etc/e-smith/templates/etc/rspamd/rspamd.conf/30Logging
Previously, `amavisd` was configured to log to maillog: I wouldn't change this convention by now.
=> Send rspamd log to /var/log/maillog

server/etc/e-smith/templates/etc/dovecot/dovecot.conf/25user-action-logs
The "append" event logs Sent mail.
Search for "save:" in /var/log/imap.
=> Log Actions: log Sent mail by default

filter/etc/e-smith/templates/etc/dnsmasq.conf/26unbound_rbl, filter/etc/e-smith/templates/etc/rspamd/rspamd.conf/20Options
Rspamd supports usage of custom DNS servers for RBL queries. We already have Unbound, we used it for spamassassin going through dnsmasq. Now we can remove the custom dnsmasq configuration and route all queries directly to Unbound.
=> rspamd: use unbound for all DNS queries (skip dnsmasq)

server/etc/e-smith/templates/etc/postfix/main.cf/30smtpauth_tls20180330
the list of weak cipher was not applied
a parameter is only for postfix >=2.11 we use 2.10
=> Remove weak cipher and unused parameter

filter/etc/e-smith/templates/etc/rspamd/rspamd.conf/60WorkerProxy
This option doesn't work as intended to create  the custom header we need (X-Spam-Flag). Therefore I would like to remove it from rspamd.conf and still continue to use the former one in milter-header.conf
https://github.com/NethServer/dev/issues/5478
=> Removal of spam_header setting

README.rst, server/etc/e-smith/db/configuration/defaults/postfix/MxRecordStatus, server/etc/e-smith/templates/etc/dnsmasq.conf/40mx_record
Since 7.5.1804 the default (and recommended setting) is `disabled` because  `enabled`
1. masquerades DNS A records in the LAN,
2. may not work with LetsEncrypt certificates,
3. may not work with GSSAPI authentication.
NethServer/dev#5490
=> MxRecordStatus default "disabled"

getmail/etc/e-smith/templates/getmailrc/40rspamd, getmail/usr/bin/rspamc-check
Avoid false positives when rspamc fails for any reason. The special exit
code 99 corresponds to a spam condition.
NethServer/dev#5513
=> Catch rspamc timeouts and other errors

common/usr/share/nethesis/NethServer/Language/en/NethServer_Module_Mail_Domain.php, common/usr/share/nethesis/NethServer/Module/Mail/Domain/Modify.php, createlinks-disclaimer, disclaimer/etc/e-smith/templates/etc/postfix/main.cf/01dkim_milter_disclaimer
This PR proposal disables the submission DKIM milter when the optional disclaimer package is installed, and reverts the fix of NethServer/dev#5514
The DKIM signature issue seems due to our Postfix configuration which double signs outbound messages:
1. the first time with `submission_smtpd_milters` (used by SMTP port 587)
2. the second time with `non_smtpd_milters` (used by `sendmail`)
```text
[root@vm8 ~]# postconf -n | grep smtpd_milt
non_smtpd_milters = unix:/var/run/opendkim/milter
smtpd_milters = unix:/var/run/rspamd/worker-proxy
submission_smtpd_milters = unix:/var/run/rspamd/worker-proxy, unix:/var/run/opendkim/milter
```
NethServer/dev#5528
=> Fix DKIM signature when disclaimer is added

server/etc/e-smith/events/actions/nethserver-mail-migrate-domains, server/etc/e-smith/events/actions/nethserver-mail-server-migrate
The sme8 migration procedure fails with nethserver-mail2-server RPM, producing the following log trace:
Jul 18 10:09:36 mail esmith::event[19980]: Can't open directory /etc/e-smith/events/nethserver-mail-server-update
Jul 18 10:09:36 mail esmith::event[19980]: Action: /etc/e-smith/events/migration-import/S30nethserver-mail-migrate-domains FAILED: 2 [0.34568]
[...]
Jul 18 10:09:36 mail esmith::event[19980]: Can't open directory /etc/e-smith/events/nethserver-mail-server-update
Jul 18 10:09:36 mail esmith::event[19980]: Action: /etc/e-smith/events/migration-import/S30nethserver-mail-server-migrate FAILED: 2 [0.152202]
As the fix is trivial I propose to trigger the `save` event because it is more quick and we will not revert the change when "mail2" is renamed "mail".
=> Fix non existing event name in mail2

filter/etc/e-smith/templates/etc/rspamd/rspamd.conf.override/10base
https://github.com/NethServer/dev/issues/5551
We must not disable the history redis storage, else the obsolete file storage is used (deprecated and less information)
=> Do not disable history stored to redis

getmail/etc/e-smith/templates/getmailrc/40rspamd, getmail/usr/bin/rspamc-getmail
Return a temporary failure condition if the spam filter fails for
an unknown reason.
NethServer/dev#5572
=> Catch rspamc errors

README.rst, migration/bayes_training.sh, nethserver-mail.spec
During upgrade from amavis to rspamd the Junk folders contents can be
used to train the Bayesian filters.
=> How to re-train Bayes filters

p3scan/usr/bin/rspamc-p3scan
As the SMTP envelope is not available, assume the message was sent from
the local host to avoid strict IP checks.
This is just an attempt to make p3scan more backward compatible with the old version.
https://github.com/NethServer/dev/issues/5606
=> Fix IP-based scoring

filter/usr/lib/systemd/system/clamd@rspamd.service.d/nethserver.conf
NethServer/dev#5610
On low resource systems the default systemd timeout can be to short to start clamd. 
You may argue you should not install it but I can't stop people from doing it anyway.
With this minor adjustment at least the clamd@rspamd.service starts up properly.
(Nice side effect is the frequency of automatic restarts are restrained a bit if something is wrong)
=> Arm integration ease timeout startup clamd

common/etc/e-smith/templates/etc/postfix/access.cidr/20TrustedNetwork
NethServer/dev#5644
do not relax helo directly like in https://github.com/NethServer/nethserver-mail/pull/92/files but push trusted network to /etc/postfix/access.cidr
=> Allow smtp access for trusted network

server/etc/e-smith/templates/etc/dovecot/dovecot.conf/10limits, server/etc/e-smith/templates/etc/dovecot/dovecot.conf/50quota, server/etc/e-smith/templates/etc/systemd/system/dovecot.service.d/limits.conf/10base
https://github.com/NethServer/dev/issues/5679
The warning prevents getmail to delete the email, fix the warning and  the emails are deleted
=> Getmail warnings prevent to delete emails in remote account 

README.rst, createlinks-server, server/etc/e-smith/db/configuration/defaults/postfix/DynamicGroupAlias, server/etc/e-smith/events/actions/nethserver-mail-server-postfix-get-group-enable, server/etc/e-smith/templates/etc/postfix/main.cf/20virtual_domains, server/usr/lib/systemd/system/postfix-get-group.socket, server/usr/lib/systemd/system/postfix-get-group@.service, server/usr/libexec/nethserver/postfix-get-group
This pull request enable postfix to create distribution lists based on system groups:
* create a service that return the users list of a group using the postfix tcp_map protocol.
* Add a systemd socket for activate the service.
* Add a prop `DynamicGroupAlias` for enable/disable the feature.
=> Add Dynamic Group Alias resolution postfix

server/etc/e-smith/templates/etc/postfix/main.cf/20virtual_domains
Use proxymap for reduce invocations of postfix-get-group service,
avoiding spamming in the system log.
see also: https://community.nethserver.org/t/sending-an-email-to-ldap-ad-group-mail-alias-is-not-a-solution/12104/45
NethServer/dev#5725
=> server: use proxymap for local group resolution

server/usr/libexec/nethserver/postfix-get-group
Add intial support for quoted string format of email address's local
part, only decode of space char (%20) are implemented.
NethServer/dev#5725
=> server: add support for space in local groups name

createlinks-server, server/etc/e-smith/templates/etc/postfix/disabled_groups/10base, server/usr/libexec/nethserver/postfix-get-group
- ignore a group alias if listed in /etc/postfix/disabled_groups
- clear Postfix address verification cache when group setup changes
This PR works with the new DB record type `group` introduced by #107 
NethServer/dev#5725
=> Disabled groups alias list

filter/etc/rspamd/local.d/classifier-bayes.conf, filter/etc/rspamd/local.d/statistic.conf, nethserver-mail.spec
Due to the upgrade of rspamd 1.9.1, we need to move the bayes expiry settings to` local.d/statistic.conf`
https://github.com/NethServer/dev/issues/5741
=> Moved bayes expiry to local.d/statistic.conf

nethserver-mail.spec
The latest smarthost package must be installed to not break the
nethserver-mail/send/read API
```text
Can't call method "get_all" on an undefined value at /usr/libexec/nethserver/api/nethserver-mail/send/read line 38, <STDIN> line 1.
```
NethServer/dev#5743
=> api. Fix smarthost DB initialization

api/send/read, nethserver-mail.spec
The `curl` command has a bad side-effect: it actually sends a (empty) message.
This PR runs the SMTP AUTH validation with `swaks` http://www.jetmore.org/john/code/swaks/
A `swaks` RPM is available from EPEL 7.
NethServer/dev#5743
=> Send SMTP AUTH probe with swaks

api/lib/mail_functions.pl, api/mailbox/read
Previously, the API didn't manage to remove the ACLs marked as deleted
from the UI.
Original code for NethGUI: https://github.com/NethServer/nethserver-mail/blob/517b89baaea06a36299783708b3dfb6091d9cf4f/server/usr/share/nethesis/NethServer/Module/MailAccount/SharedMailbox/Edit.php#L99
=> api public mailboxes: remove delete ACL

getmail/etc/e-smith/templates/var/lib/nethserver/sieve-scripts/before.sieve/30getmailFilter, server/etc/e-smith/templates/var/lib/nethserver/sieve-scripts/before.sieve/20junkmail, server/etc/e-smith/templates/var/lib/nethserver/sieve-scripts/before.sieve/40junkmail
nethserver-mail-getmail has for dependency nethserver-mail-server, we could move the fragment to the nethserver-mail-server, but we need to put the sieve filter of server after the sieve filter of getmail (else the subject won't be rewritten by the sieve filter, it could be moved first to junk)
We only look after the headers X-Spam-Flag or X-Spam to move the email to junk
https://github.com/NethServer/dev/issues/5771
=> Move to junk only if the headers match

createlinks-filter, filter/etc/e-smith/templates/etc/rspamd/local.d/antivirus.conf/10base, filter/etc/e-smith/templates/etc/rspamd/local.d/settings.conf/10AuthenticatedUser
https://github.com/NethServer/dev/issues/5773
I need a template due to nethserver-mail-quarantine which use also local.d/settings.conf
the symbol `CLAM_VIRUS_FAIL(0.00){failed to scan and retransmits exceed;}` is still added but the force action we made on this symbol is deactivated for authenticated users
check maillog : https://gist.github.com/stephdl/de6fc5fcfaffac48d654d26b44ad151f
=> Do not soft reject for authenticated users

api/lib/mail_functions.pl, api/pseudonym/read, ui/src/views/Addresses.vue
-  mail alias creation validator: an external address alone is not allowed
- mail alias edit: an external address is displayed without domain suffix
=> Minor cockpit fixes

createlinks-filter, filter/etc/e-smith/templates/etc/rspamd/forbidden_file_extension.map/10base, filter/etc/e-smith/templates/etc/rspamd/local.d/mime_types.conf/10base, filter/etc/e-smith/templates/etc/rspamd/local.d/multimap.conf/10base, filter/etc/rspamd/local.d/force_actions.conf
When we decide to reject Exec or Arch, we add a new setting to put a 20x multiplicator to reject MIME detected
As a side note we have a lot more MIME that we could detect, for example I added `js` and `jar` for the to the bad extensions
please check the code at https://github.com/rspamd/rspamd/blob/master/src/plugins/lua/mime_types.lua
The custom extension could not be added here, we cannot be sure that it could not break rspamd.
When I put a not desired MIME xlsx inside an archive now it is rejected -> https://gist.github.com/812e6c7d35e90e09a6bd72eb2ea358f1
https://github.com/NethServer/dev/issues/5779
=> Reject forbidden MIME with SMTP message

api/filter/update, createlinks-filter, filter/etc/e-smith/db/configuration/defaults/clamd@rspamd/status, filter/etc/e-smith/db/configuration/defaults/clamd@rspamd/type, filter/etc/e-smith/templates/etc/rspamd/local.d/force_actions.conf/10base, filter/etc/e-smith/templates/etc/rspamd/local.d/settings.conf/10AuthenticatedUser, filter/usr/lib/systemd/system/rspamd.service.d/nethserver.conf
- clamd@rspamd instance is now restarted on every nethserver-mail-filter-save event
- clamd@rspamd is no more a required service for rspamd
- if antivirus check is disabled, clamd@rspamd is stopped
See also NethServer/nethserver-antivirus#4
NethServer/dev#5803
=> Restart clamd rspamd instance on nethserver-antivirus-update

getmail/etc/e-smith/templates/etc/cron.d/getmail/10base
getmail connection errors go to syslog (and then to maillog) instead of sending a mail to root
syadmin is used to look for errors in maillog, not in root mail archive
Moreover, getmail already logs some of its messages to maillog, this
pull request will unify behavior
NethServer/dev#5815
=> getmail: log errors to syslog

api/mailbox/read
Even if `DynamicGroupAlias` is disabled, the list of existing groups
is used to configure ACLs on public mailboxes.
NethServer/dev#5833
=> api: always list available groups

api/mailbox/create, api/mailbox/validate
- invoke pseudonym-create event
- correctly validate acl rights
NethServer/dev#5834
=> Shared mailbox api: fix creation

api/connectors/read, nethserver-mail.spec
Do not fail with error like:
curl: (6) Could not resolve host: domain.org:mypass@192.168.5.1.1; Unknown error
Add some perl magic using IPC::Run to protect the input from shell
injection.
NethServer/dev#5873
=> api connectors: correctly handle username with '@'

createlinks-filter, filter/etc/e-smith/templates/etc/opt/olefy/olefy.conf/10base, filter/etc/e-smith/templates/etc/rspamd/local.d/external_services.conf/10base, nethserver-mail.spec
The new Olefy 1.0.1 package fixes a TCP port conflict. The port 10632 is
the new (unassigned) port number.
NethServer/dev#5963
=> Upgrade default Olefy listen port

server/etc/e-smith/events/actions/nethserver-mail-account-cleanup
The mail home directory is not deleted if the event is invoked in
short user name form.  Other actions acting on user accounts assume a
short user name is passed for historical reasons. If a long user name
form is given, the `@domain` suffix is trimmed.
NethServer/dev#6030
=> Fix short account name support

filter/etc/e-smith/templates/etc/rspamd/rspamd.conf/20Options, getmail/etc/e-smith/templates/var/lib/nethserver/sieve-scripts/before.sieve/30getmailFilter, getmail/usr/bin/rspamc-getmail, p3scan/usr/bin/rspamc-p3scan
The current code does not handle "soft reject" responses from rspamd, that might happen if ClamAV does not reply in 8 seconds (for instance).
This PR ensures an exit code is returned to getmail if a "soft reject" occurs, so the mail is not expunged from the remote server and a delivery is attempted at a later step.
It is an alternative solution to #183 
https://github.com/NethServer/dev/issues/6052
=> Handle rspamd "soft reject" responses

README.rst, server/etc/e-smith/templates/etc/dovecot/dovecot.conf/50vsz_limit
When VszLimit prop is empty (default), dovecot will use its default
value for 'default_vsz_limit' option.
Otherwise, VszLimit can have an integer value expressed in 'M' unit.
This implemention preserve the current behavior and should also
avoid conflicts with existing template customs.
The VszLimit prop should be changed only when users have hundreds of
thousands mails inside the INBOX.
The evidence is an error like:
Error: mmap() failed with file  [..]/Maildir/dovecot.index.cache: Cannot allocate memory
=> Add VszLimit property

README.rst, server/etc/e-smith/templates/etc/dovecot/dovecot.conf/10limits_local
Some web mail clients can creates many connections quickly reaching
the maximum value of mail_max_userip_connection option.
This is a common situation when using WebTop with shared accounts.
This commits statically sets a limit for localhost which is 5 times
higer than the value of MaxUserConnectionsPerIp property.
Such configuration should fit most usage scenarios.
If an higher limit for localhost is needed, just increase the existing
MaxUserConnectionsPerIp property.
=> Set MaxUserConnectionsPerIp for localhost

server/etc/e-smith/templates/etc/dovecot/dovecot.conf/10limits
Dovecot doesn't accept an 'imap' section followed by a remote one.
This new configuration applies the global limit to all type connections without matching the protocol.
See also https://doc.dovecot.org/configuration_manual/config_file/config_file_syntax/
Following configurations are *not* valid:
```
imap {
mail_max_userip_connections = ..
}
remote x.x.x.x {
imap {
mail_max_userip_connections = ..
}
}
```
```
imap {
mail_max_userip_connections = ..
}
remote x.x.x.x {
mail_max_userip_connections = ..
}
```
```
imap {
mail_max_userip_connections = ..
}
local 127.0.0.1 {
remote 127.0.0.1 {
mail_max_userip_connections = 60
}
}
```
=> dovecot.conf: set max_userip for all protocols

api/pseudonym/read, ui/public/i18n/language.json, ui/src/views/Addresses.vue
Show addresses of deleted users if a corresponding entry in `accounts` database exists.
The entry in `accounts` database exists if the mailbox of the user was configured (e.g. the mailbox was disabled, a custom quota was set, etc).
The address/account of a deleted user can be preserved (in order to restore its configuration whenever the related user is created again) or it can be deleted from the UI.
NethServer/dev#6164
=> Show addresses of deleted users

ui/src/views/Send.vue
Doc info title inside the Relay page shows always `Sender` label also if `Recipient` is selected
=> ui. fix doc info title in relay

api/imapsync/execute, api/imapsync/read, api/imapsync/update
From imapsync FAQ:
```
Q. On Unix, some passwords contain some weird *(),;&~ characters.
Login fails.
...
R2. If R1 fails, with very old imapsync or old Mail::IMAPClient Perl module,
try also using double-quotes within single-quotes. It will enclose
the password within double-quotes in the imap LOGIN command:
```
The fix has been released on Mail::IMAPClient 3.38, while EPEL has 3.37
release
See also https://imapsync.lamiral.info/FAQ.d/FAQ.Passwords_on_Unix.txt
NethServer/dev#6233
=> imapsync: workaround IMAPClient password bug

api/domains/read
There is a missing "domain database" parameter assignment in the method invocation.
https://github.com/NethServer/dev/issues/6282
=> Fix get_account_object() invocation

api/imapsync/read, api/imapsync/update, imapsync/usr/lib/systemd/system/imapsync@.service, ui/public/i18n/language.json, ui/src/views/Imapsync.vue
The PR provides a textarea to exclude folders from the synchronization, it match a regex rule, so all folder matching `Foo` in the name will be excluded of synchronization, to be exclusive you need to use `^Foo$`
we need a hack for the exclusion list, if you end the list with `|` then all folders are excluded. So if the exclusion exists, then we add `|` at the beginning 
https://github.com/NethServer/dev/issues/6306
=> Imapsync exclude folders of synchronization

api/imapsync/execute, api/imapsync/read, api/imapsync/update
When a user uses a `"` in a password, we breack imapsync because due to a bug in the perl library Mail::IMAPClient 3.37 we have to enclose the password inside double quote 
https://imapsync.lamiral.info/FAQ.d/FAQ.Passwords_on_Unix.txt
So we need to quote all double quote we can find in the user's password, ecept the first and the last we write in `/var/lib/nethserver/umapsync/user.pwd`
https://github.com/NethServer/dev/issues/6303
=> Imapsync: Quote " when present in an user  password

api/imapsync/read, api/imapsync/update
The imapsync passfile must be saved in UTF8, perl do not do it explicitly.
https://github.com/NethServer/dev/issues/6308
=> Save the imapsync passfile in utf8

server/etc/e-smith/events/actions/nethserver-mail-quota-recalc
Ensure a valid user is passed (and not a group name) before invoking `doveadm quota recalc`.
https://github.com/NethServer/dev/issues/6310
=> Fix quota recalc for groups

api/imapsync/read, api/imapsync/update
=> Use passfile for the count messages features

imapsync/usr/lib/systemd/system/imapsync@.service
https://github.com/NethServer/dev/issues/6306
The regex rule is too exclusive subfolders are included in the synchronization see https://github.com/NethServer/dev/issues/6306#issuecomment-710189784
=> Allow to exclude subfolders of  synchronization

api/imapsync/read
https://github.com/NethServer/dev/issues/6306
The Exclude  is correctly read from readInput and correctly saved inside esmith database but the exclude string read from esmith database is badly encoded and given to the UI in characters not in UTF8
=> Decode UTF8 string of Exclude

filter/etc/e-smith/templates/etc/rspamd/local.d/external_services.conf/10base
The oletools extended mode can reject more macro when turned to true, however the default olefy rpm does not reject recent macro we could use also a fork
https://github.com/NethServer/olefy/pull/5
https://github.com/NethServer/dev/issues/6321
=> Enable the oletools extended mode

api/mailbox/read
Return a Mailboxes object with the expected attributes to avoid undefined assignments on the UI side.
NethServer/dev#6366
=> Fix error with missing account provider

api/imapsync/read, api/imapsync/update, imapsync/usr/lib/systemd/system/imapsync@.service, ui/public/i18n/language.json, ui/src/views/Imapsync.vue
The Trash folder might be synchronized, depended on the need of the system administrator. The PR intends to synchronize the folder on an administrator input, the default is the Trash sync is disabled
https://github.com/NethServer/dev/issues/6376
=> Dynamic exclusion of Trash folder

api/pseudonym/update
When changing the Access property of group pseudonym,
the change should not be propagated to the destination aliases:
a public pseudonym can always be used to deliver messages to a private
pseudonym.
NethServer/dev#6391
=> pseudonym api: do not propagate Access prop

filter/etc/e-smith/templates/etc/rspamd/rspamd.conf/20Options
In log we can find this now with rspamd 2.5 version
```
Jan 26 17:24:12 ns7loc10 rspamd[4786]: <uj7j5n>; cfg; dkim_module_config: init internal dkim module
Jan 26 17:24:12 ns7loc10 rspamd[4786]: <uj7j5n>; cfg; rspamd_init_filters: requested unknown module spf
```
Originally rspamd started with C plugin that are now replaced by LUA plugin, with the version > 2.3, SPF is now  a LUA plugin
See 
https://rspamd.com/doc/modules/
`spf: checks SPF records for messages processed. Since rspamd 2.3, this C module has been removed and replaced by an equivalent Lua module.`
This plugin is enabled by default
`Jan 26 17:24:12 ns7loc10 rspamd[4786]: <uj7j5n>; cfg; rspamd_init_lua_filters: init lua module spf from /usr/share/rspamd/plugins/spf.lua; digest: 1fcdf00ca4` …
=> Spf is now a lua plugin after 2.3 version

api/pseudonym/validate, ui/public/i18n/language.json
The PR adds a validation check that forbids external addresses pointing to the mail address itself.
For example, if mail address is wildcard `add@` and the local domains are `example.com` and `example.test`:
- external destination `add@other.test` is allowed
- external destination `add@example.test` is forbidden
https://github.com/NethServer/dev/issues/6464
=> Prevent self-loops in mail address destinations

api/domains/read
https://github.com/NethServer/dev/issues/6472
We have to remove spaces to compare between the key and the  dig output
to test the patch 
`echo '{"action":"network-checks","domain":"domain.com"}'| /usr/libexec/nethserver/api/nethserver-mail/domains/read`
=> Remove spaces to compare DKIM

filter/etc/e-smith/templates/etc/rspamd/local.d/antivirus.conf/10base
Rspamd uses wrong esmith property in the template /etc/rspamd/local.d/antivirus.conf
https://github.com/NethServer/dev/issues/6527
=> Fix bad esmith property for clamav (rspamd key)

createlinks-filter, filter/etc/e-smith/templates/etc/rspamd/local.d/groups.conf/10NethserverGroups, filter/etc/rspamd/scores.d/nethserver_group.conf, nethserver-mail.spec
We need to set score to the symbol of YOMI else we have traces in logs. Therefore this file must be a template.
this is the log traces in maillog
```
Jun 28 15:20:03 ns7dev13 rspamd[5057]: <2270b8>; proxy; lua_task_insert_result_common: symbol insertion issue: unknown symbol YOMI_CLEAN; trace: [1]:{/usr/share/rspamd/lualib/lua_scanners/yomi.lua:122 - handle_yomi_result [Lua]}; [2]:{/usr/share/rspamd/lualib/lua_scanners/yomi.lua:463 - <unknown> [Lua]};
Jun 28 15:20:00 ns7dev13 rspamd[5057]: <2270b8>; proxy; lua_task_insert_result_common: symbol insertion issue: unknown symbol YOMI_SKIPPED; trace: [1]:{/usr/share/rspamd/lualib/lua_scanners/yomi.lua:271 - fn [Lua]}; [2]:{/usr/share/rspamd/lualib/lua_scanners/yomi.lua:212 - callback [Lua]}; [3]:{/usr/share/rspamd/lualib/lua_redis.lua:917 - …
```
=> Yomi needs local.d/groups.conf as a template

createlinks-filter, filter/etc/rspamd/local.d/groups.conf, filter/etc/rspamd/scores.d/nethserver_group.conf, nethserver-mail.spec
Reverts NethServer/nethserver-mail#249
The PR tried to suppress a warning that is generated on each received mail:
> lua_task_insert_result_common: symbol insertion issue: unknown symbol YOMI_CLEAN
Still, the change breaks all scores from https://github.com/nethesis/yomi-rspamd
NethServer/dev#6535
=> Revert "Yomi needs local.d/groups.conf as a template"

filter/etc/httpd/admin-conf.d/rspamd.conf
With the split of nethserver-httpd-admin and nethserver-httpd-service we have a forbidden proxypass rule that we use to hide the scores in the rspamd UI. We have to enable the `SymLinksIfOwnerMatch` (more secure that FollowSymLinks)   to make the proxypass workable
We can find an error logged on /var/log/httpd-admin/error_log explains it:
`[rewrite:error] [pid 32170] [client 192.168.2.61:44806] AH00670: Options FollowSymLinks and SymLinksIfOwnerMatch are both off, so the RewriteRule directive is also forbidden due to its similar ability to circumvent directory restrictions : /etc/httpd/htdocs, referer: https://192.168.2.61:980/rspamd/`
nethgui [allows](https://github.com/NethServer/nethserver-httpd-admin/blob/master/nethgui/etc/e-smith/templates/etc/httpd/admin-conf/httpd.conf/60NethServer …
=> The rewrite rule of rspamd needs FollowSymlinks

filter/etc/rspamd/local.d/groups.conf
Following the [documentation](https://rspamd.com/doc/modules/reputation.html) the reputation plugin needs to get default weight set in the local.d/groups.conf
If we do not set it we have a warning seen in maillog and the default score  set is 0.0, this break the reputation plugin because it is not able to adjust the score following the reputation of the sender.
https://github.com/NethServer/dev/issues/6567
=> Default weight for the reputation plugin

api/connectors/read
Due to old curl release, the check-credentials action could fail
to authenticate while getmail can correctly download the messages.
Replace curl with a temporary one-time execution of getmail.
Such run will try to download fewest bytes as possible.
NethServer/dev#6577
=> connectors api: improve check-credentials

ui/src/views/Settings.vue
Users are requesting more option to send email, we have a gap to fill between 20MB to 50MB. I added too a 75 MB option
`:data="[10,20,25,30,35,40,45,50,75,100,200,500,1000]"`
https://community.nethserver.org/t/numeric-input-field-for-maximum-message-size-or-a-finer-adjustment-in-the-slider/19147
https://github.com/NethServer/dev/issues/6592
=> More options for MessageSizeMax to send email

api/pseudonym/create
Something Fun, the type property becomes `null` even if I can see it when I print the value of `$record` I fixed the issue by rewriting the new_record
```
[root@ns7loc9 ~]#  echo '{"action":"create-pseudonym","domains":["de-labrusse.fr","nethservertest.org"],"Description":"","Access":"public","Account":[{"name":"stephane@nethservertest.org","displayname":"stephane","type":"user"}],"name":"prout"}' | /usr/bin/setsid /usr/bin/sudo /usr/libexec/nethserver/api/nethserver-mail/pseudonym/create 
Accountstephane@nethservertest.orgtypepseudonymDescriptionAccesspublic
Accountstephane@nethservertest.orgtypepseudonymDescriptionAccesspublic
Accountstephane@nethservertest.orgtypepseudonymDescriptionAccesspublic
Accountstephane@nethservertest.orgtypepseudonymDescriptionAccesspublic
ERROR: You should …
```
=> Fix type property that becomes null

filter/etc/e-smith/templates/etc/rspamd/local.d/antivirus.conf/10base, filter/etc/e-smith/templates/etc/rspamd/rspamd.conf/20Options
Clamav timeout is 90 seconds (45s x 2, due to 1 retransmit).
Task timeout should be greater (91s).
90 seconds spent during an SMTP transaction are common.
Note that a bigger timeout with less retransmit is more resource efficient.
https://github.com/NethServer/dev/issues/6659
=> Increase clamav and task timeout

ui/src/views/Addresses.vue
Refresh openCreateAddress selectpicker to avoid inconsistent view after adding first address. Refer to https://github.com/NethServer/dev/issues/6739
=> ui. refresh selectpicker on openCreateAddress
