NethServer/nethserver-mail

- README.rst
> Upgrade to rspamd instructions

- createlinks-filter
- filter/etc/e-smith/templates/etc/httpd/admin-conf.d/rspamd.conf/10base
> Limit rspamd UI access by IP from trusted networks

- createlinks-filter
https://github.com/NethServer/dev/issues/5394
> corrected typo to rspamd web conf

- nethserver-mail2.spec
Fix installation conflicts with nethserver-getmail RPM
> Provide RPM conflicting symbols

- .tx/config
- README.rst
- createlinks-getmail
- getmail/etc/e-smith/events/actions/nethserver-getmail-conf
- getmail/etc/e-smith/events/actions/nethserver-getmail-migrate
- getmail/etc/e-smith/events/actions/nethserver-getmail-migrate-ns6
- getmail/etc/e-smith/templates/etc/cron.d/getmail/10base
- getmail/etc/e-smith/templates/etc/dovecot/dovecot.conf/60lda
- getmail/etc/e-smith/templates/getmailrc/00template_vars
- getmail/etc/e-smith/templates/getmailrc/10retriever
- getmail/etc/e-smith/templates/getmailrc/20destination
- getmail/etc/e-smith/templates/getmailrc/40rspamd
- getmail/etc/e-smith/templates/getmailrc/50options
- getmail/usr/share/nethesis/NethServer/Help/en/NethServer_Module_Getmail.rst
- getmail/usr/share/nethesis/NethServer/Language/en/NethServer_Module_Getmail.php
- getmail/usr/share/nethesis/NethServer/Module/Getmail.php
- getmail/usr/share/nethesis/NethServer/Module/Getmail/Modify.php
- getmail/usr/share/nethesis/NethServer/Module/Getmail/ToggleEnable.php
- getmail/usr/share/nethesis/NethServer/Template/Getmail/Modify.php
- getmail/usr/share/nethesis/NethServer/Template/Getmail/ToggleEnable.php
- nethserver-mail2.spec
> Import getmail

- filter/etc/rspamd/local.d/milter_headers.conf
https://github.com/NethServer/dev/issues/5394
> extended_spam_headers = true

- getmail/usr/share/nethesis/NethServer/Help/en/NethServer_Module_Getmail.rst
- getmail/usr/share/nethesis/NethServer/Language/en/NethServer_Module_Getmail.php
> Rename getmail email filter UI label

- filter/etc/backup-config.d/nethserver-mail-filter.include
- filter/etc/backup-data.d/nethserver-mail-filter.exclude
- filter/etc/backup-data.d/nethserver-mail-filter.include
- filter/etc/backup-data.d/rspamd.exclude
- filter/etc/backup-data.d/rspamd.include
- filter/etc/e-smith/templates/etc/rspamd/rspamd.conf/20Options
Change path for `control_socket` to `/var/run/rspamd/control`
> Split configuration for data/config backups

- p3scan/opt/puppetlabs/puppet/lib/ruby/2.1.0/facter/p3scan.rb
> Import p3scan.rb inventory plugin (mail2)

- createlinks-server
- server/etc/e-smith/templates/etc/postfix/main.cf/30smtpauth_tls20180330
https://github.com/NethServer/dev/issues/5438
cipher of category B from  https://bettercrypto.org/static/configuration/MailServers/Postfix/main.cf
> Hardening tls smtpd

- filter/etc/httpd/admin-conf.d/rspamd.conf
https://github.com/NethServer/dev/issues/5437
> Read and save actions are disabled in rspamd webUI

- disclaimer/etc/e-smith/templates/etc/postfix/master.cf/01TemplateDisclaimer_vars
https://github.com/NethServer/dev/issues/5452
> Replace break by last

- filter/etc/e-smith/templates/etc/rspamd/rspamd.conf/50WorkerController
- filter/etc/e-smith/templates/etc/rspamd/rspamd.conf/60WorkerProxy
- filter/etc/e-smith/templates/etc/rspamd/rspamd.conf/70WorkerFuzzy
https://github.com/NethServer/dev/issues/5478
> Rspamd 1.7.4 worker change

- .tx/config
With the change of the nethserver-mail2, the root folder doesn't exist, this is a fix.
Do we need an issue in the bug tracker for this @DavidePrincipi
> nethserver-mail: Fix transifex Config file

- getmail/usr/share/nethesis/NethServer/Template/Getmail/Modify.php
(optional)
https://github.com/NethServer/dev/issues/5554
> mask password field

- filter/etc/e-smith/templates/etc/rspamd/rspamd.conf/20Options
https://github.com/NethServer/dev/issues/5551
> Display filters only if SpamCheckStatus is enabled

- server/etc/e-smith/templates/var/lib/nethserver/sieve-scripts/before.sieve/10junkmail
https://github.com/NethServer/dev/issues/5562
> Check if rspamd is installed before to enable the sieve script

- createlinks-filter
https://github.com/NethServer/dev/issues/5562
> Expand sieve script with filters rpm installation

- createlinks-filter
- filter/usr/share/nethesis/NethServer/Language/en/NethServer_Module_Mail_Filter.php
- filter/usr/share/nethesis/NethServer/Module/Mail/Filter.php
- server/etc/e-smith/templates/var/lib/nethserver/sieve-scripts/before.sieve/10junkmail
https://github.com/NethServer/dev/issues/5562
> Subject Lenght UI validator and status watch

- nethserver-mail2.spec
https://github.com/NethServer/dev/issues/5562
> mail2-common creates the sieve-scripts folder

- server/usr/share/nethesis/NethServer/Module/MailAccount/User/Modify.php
https://github.com/NethServer/dev/issues/5566
> User quota set to a maximum of 100GB

- filter/etc/httpd/admin-conf.d/rspamd.conf
https://github.com/NethServer/dev/issues/5561
> Return 200, UI expects it for GET actions

- createlinks-getmail
- getmail/etc/e-smith/templates/getmailrc/40rspamd
- getmail/etc/e-smith/templates/var/lib/nethserver/sieve-scripts/before.sieve/30getmailFilter
- server/etc/e-smith/templates/etc/dovecot/dovecot.conf/60lmtp
- server/etc/e-smith/templates/var/lib/nethserver/sieve-scripts/before.sieve/10junkmail
- server/etc/e-smith/templates/var/lib/nethserver/sieve-scripts/before.sieve/10sieveExtensions
- server/etc/e-smith/templates/var/lib/nethserver/sieve-scripts/before.sieve/20junkmail
https://github.com/NethServer/dev/issues/5572
> Rewrite subject by rspamd header and sieve

- getmail/etc/e-smith/templates/var/lib/nethserver/sieve-scripts/before.sieve/30getmailFilter
> rewrite subject is out of move logic spam

- common/etc/e-smith/templates/etc/sysconfig/sa-update/10base
- createlinks-common
https://github.com/NethServer/dev/issues/5605
> Disable the cron job sa-update

- README.rst
- createlinks-server
- createlinks-smarthost
- smarthost/etc/e-smith/templates/etc/postfix/canonical/10root_map
- smarthost/etc/e-smith/templates/etc/postfix/main.cf/40sender_maps
See also NethServer/nethserver-base#139
NethServer/dev#5614
> smarthost: support root sender remapping

- filter/etc/e-smith/templates/etc/rspamd/local.d/antivirus.conf/10base
- filter/etc/e-smith/templates/etc/rspamd/rspamd.conf/20Options
- nethserver-mail.spec
https://github.com/NethServer/dev/issues/5608
> Upgrade to rspamd-1.8.1

- server/etc/e-smith/events/actions/nethserver-mail-shrmbx-delete
https://github.com/NethServer/dev/issues/5671
> Delete recursively and unsubscribe to shared mailbox

- common/etc/e-smith/templates/etc/postfix/master.cf/60NoTLSAuthentification
https://github.com/NethServer/dev/issues/5672
> SASL on 10587 without TLS on localhost only

- server/etc/e-smith/templates/etc/dovecot/dovecot.conf/30quota
- server/etc/e-smith/templates/etc/dovecot/dovecot.conf/50quota
Define the value of the global mail_plugins parameter before using it in
configuration subsections.
NethServer/dev#5697
> Fix quota calculation regression

- server/etc/e-smith/templates/etc/postfix/login_maps/10MailAliases
https://github.com/NethServer/dev/issues/5672
> Fix missing array

- server/etc/e-smith/templates/etc/postfix/login_maps/10MailAliases
The Account validation must be repeated for each comma-separated list
value. The fixed code was testing only the last item.
NethServer/dev#5672
> Fix login_maps expansion

- README.rst
> Dev docs for SenderValidation prop

- filter/etc/rspamd/local.d/redis.conf
https://github.com/NethServer/dev/issues/5722
> Increased the redis timeout to 10s

- README.rst
- server/etc/e-smith/templates/etc/postfix/internal_access/10groups_private
>  Private group addresses general switch 

- nethserver-mail.spec
All updated machines will automatically get Cockpit UI
> spec: merge ui package into common

- api/domains/read
- api/mailbox/read
- api/pseudonym/read
Requires https://github.com/NethServer/nethserver-cockpit/pull/85
> Fix no accounts provider use case

- api/send/read
- smarthost/etc/e-smith/templates/etc/postfix/sasl_passwd/10smarthost_password_sender
- ui/src/views/Send.vue
- Run check only if both host name and port are filled
- Port input integer
- Clear validation status during edit/create
- (API) Fix anonymous smarthost checking and sasl_passwd template
NethServer/dev#5743
> Fix send validation

- filter/etc/rspamd/local.d/force_actions.conf
https://github.com/NethServer/dev/issues/5755
> Soft reject if CLAM_VIRUS_FAIL

- filter/etc/e-smith/templates/etc/rspamd/rspamd.conf/20Options
https://github.com/NethServer/dev/issues/5761
> Fix path for effective_tld_names.dat

- filter/etc/e-smith/templates/etc/rspamd/local.d/antivirus.conf/10base
https://github.com/NethServer/dev/issues/5769
> Timeout and retransmits settings for clamd

- server/etc/e-smith/events/actions/nethserver-mail-shrmbx-cfgbackup
> Do not unquote input filenames

- filter/etc/e-smith/templates/etc/rspamd/local.d/multimap.conf/10base
https://github.com/NethServer/dev/issues/5811
> Smtp rejection message for multimap

- filter/etc/e-smith/templates/etc/rspamd/local.d/multimap.conf/10base
https://github.com/NethServer/dev/issues/5811
> Reject blacklisted domains without score

- server/etc/e-smith/templates/etc/dovecot/quota.passwd/10base
https://github.com/NethServer/dev/issues/5837
> Set the custom quota to the short name format

- common/etc/sudoers.d/50_nsapi_nethserver_mail
- nethserver-mail.spec
> Cockpit Email app config for sudoers delegation

- ui/src/views/Settings.vue
https://github.com/NethServer/dev/issues/5805
> Add sudo to update api of settings

- api/mailbox/validate
- ui/src/views/Mailboxes.vue
Avoid warnings in browser console
> Fix undefined vars in Maiboxes

- api/mailbox/read
- server/etc/cron.daily/nethserver-mail-spam-expunge
- server/etc/e-smith/events/actions/nethserver-mail-server-init-acl
- server/usr/share/nethesis/NethServer/Language/en/NethServer_Module_MailAccount_SharedMailbox.php
- server/usr/share/nethesis/NethServer/Module/MailAccount/SharedMailbox.php
- server/usr/share/nethesis/NethServer/Module/MailAccount/SharedMailbox/Edit.php
- server/usr/share/nethesis/NethServer/Module/MailAccount/SharedMailbox/SharedMailboxAdapter.php
- ui/public/i18n/language.json
- ui/src/views/Mailboxes.vue
https://github.com/NethServer/dev/issues/5843
> Display Junk public mailbox in read-only state

- api/mailbox/validate
- ui/src/views/Mailboxes.vue
- API: allow ACLs for root user
- API: passthrough "custom" ACLs
- UI: make "custom" ACLs immutable
NethServer/dev#5843
> Fix custom ACLs entries for public mailboxes

- filter/etc/rspamd/local.d/milter_headers.conf
https://github.com/NethServer/dev/issues/5852
> Add score header for authenticated user or local IP

- api/mailbox/read
> api mailbox: avoid log noise

- smarthost/etc/e-smith/templates/etc/postfix/main.cf/40smarthost_sender
- smarthost/etc/e-smith/templates/etc/postfix/sasl_passwd/10smarthost_password_sender
https://github.com/NethServer/dev/issues/5888
Do not squash-merge. Preserve the patch author.
> Fix smtp client auth with multiple senders

- api/mailbox/read
> api: fix pseudonym filter for public mailbox

- createlinks-filter
- filter/etc/e-smith/templates/etc/rspamd/blacklist_from.map/10base
- filter/etc/e-smith/templates/etc/rspamd/blacklist_from_domains.map/10base
- filter/etc/e-smith/templates/etc/rspamd/blacklist_from_subdomains.map/10base
- filter/etc/e-smith/templates/etc/rspamd/local.d/multimap.conf/10base
- filter/etc/e-smith/templates/etc/rspamd/whitelist_from.map/10base
- filter/etc/e-smith/templates/etc/rspamd/whitelist_from_domains.map/10base
- filter/etc/e-smith/templates/etc/rspamd/whitelist_from_subdomains.map/10base
- filter/etc/e-smith/templates/etc/rspamd/whitelist_ip.map/10base
- filter/etc/e-smith/templates/etc/rspamd/whitelist_to.map/10base
- filter/etc/e-smith/templates/etc/rspamd/whitelist_to_domains.map/10base
- filter/etc/e-smith/templates/etc/rspamd/whitelist_to_subdomains.map/10base
Sort subdomains and domain, then expand them in separate map, the multimap has been modified to whitelist or blacklist subdomain 
https://github.com/NethServer/dev/issues/5940
> Wl bl sub domain

- ui/src/views/Filter.vue
When you try to delete a rules in Filters page, you'll able to delete only the last.
This fix the problem.
Refer to https://github.com/NethServer/dev/issues/5951
> ui. fix rules removal problem

- ui/src/views/Connectors.vue
Fix FilterCheck status on Cockpit interface. Now the checkbox is valued properly.
Refer to https://github.com/NethServer/dev/issues/5952
> ui. filtercheck is not shown properly

- filter/etc/e-smith/templates/etc/rspamd/local.d/multimap.conf/10base
- filter/etc/rspamd/local.d/force_actions.conf
> Same symbol for domain|sub.domain WL|BL

- filter/etc/e-smith/templates/etc/rspamd/local.d/multimap.conf/10base
- filter/etc/rspamd/local.d/force_actions.conf
NethServer/dev#5940
Alternative to #173
> Revert "Same symbol for domain|sub.domain WL|BL"

- ui/src/views/Addresses.vue
- ui/src/views/Dashboard.vue
- ui/src/views/Domains.vue
- ui/src/views/Mailboxes.vue
- ui/src/views/Queue.vue
- ui/src/views/Settings.vue
Refer to https://github.com/NethServer/dev/issues/6004
> ui. change h1 to h2 html tags

- ui/public/i18n/language.json
- ui/src/components/ModalDkimEdit.vue
https://github.com/NethServer/dev/issues/6036
> Set DKIM default key to default._domainkey

- ui/src/components/ModalDkimEdit.vue
Reverts NethServer/nethserver-mail#177
> Revert "Set DKIM default key to default._domainkey"

- README.rst
- server/etc/e-smith/db/configuration/defaults/dovecot/SharedSeen
- server/etc/e-smith/templates/etc/dovecot/dovecot.conf/40namespaces
https://github.com/NethServer/dev/issues/6064
> Add Shared Seen support

- api/filter/update
- ui/src/views/Filter.vue
Fixed BlockAttachmentCustomList prop saving event.
Refer to https://github.com/NethServer/dev/issues/6073
> ui & api. fix filter save event

- filter/opt/puppetlabs/puppet/lib/ruby/2.1.0/facter/mails.rb
Counter number of mail in the last 24 hours:
- total mails
- sent mails
- received mails
- mails with attachments
Such counter will be used to suggest plans for users who want to buy Yomi sandbox for rspamd.
> facter: add mail counters

- server/etc/e-smith/db/configuration/defaults/dovecot/LogActions
- server/etc/e-smith/db/configuration/defaults/dovecot/SharedSeen
Enable LogActions and SharedSeen
> New dovecot defaults

- getmail/etc/e-smith/templates/getmailrc/40rspamd
- getmail/usr/share/nethesis/NethServer/Module/Getmail/Modify.php
- ui/public/i18n/language.json
- ui/src/views/Connectors.vue
- Disable filter by default
- Show info tip when filter is enabled
> New getmail defaults

- filter/etc/rspamd/scores.d/nethserver_group.conf
force the weight of SPOOF_REPLYTO to 3
> Score of SPOOF_REPLYTO is 3

- server/etc/e-smith/templates/etc/dovecot/dovecot.conf/10distro-tls_20180621
- server/etc/e-smith/templates/etc/dovecot/dovecot.conf/10distro-tls_20200510
- server/etc/e-smith/templates/etc/postfix/main.cf/30smtpauth_tls20180621
- server/etc/e-smith/templates/etc/postfix/main.cf/30smtpauth_tls20200510
- smarthost/etc/e-smith/templates/etc/postfix/main.cf/40enableTLS
- smarthost/etc/e-smith/templates/etc/postfix/main.cf/40enableTLS20180330
- smarthost/etc/e-smith/templates/etc/postfix/main.cf/40enableTLS20200510
> New policy 20200510 only TLS 1.2

- server/etc/e-smith/templates/etc/postfix/main.cf/30smtpauth_tls20200510
- smarthost/etc/e-smith/templates/etc/postfix/main.cf/40enableTLS20200510
https://github.com/NethServer/dev/issues/6170
> Remove anonymous ciphers for postfix

- server/usr/libexec/nethserver/imapsieve/spam-training
https://github.com/NethServer/dev/issues/6200
> Do not train rspamd if SpamCheckStatus is disabled

- filter/etc/e-smith/templates/etc/rspamd/rspamd.conf.override/10base
- server/usr/libexec/nethserver/imapsieve/spam-training
https://github.com/NethServer/dev/issues/6200
> Dovecot cannot read esmith db for SpamCheckStatus

- ui/src/filters.js
- ui/src/views/Dashboard.vue
Make statistics numbers easily readable.
E.g: display **14 K connections** instead of **14536 connections**
NethServer/dev#6206
> Display numbers in a human readable form

- api/imapsync/update
https://github.com/NethServer/dev/issues/6306
> Cosmetic fixes for the systemD Env file

- api/imapsync/read
- api/imapsync/update
Force creation of imapsync database with UTF8 encoding
> imapsync: handle UTF8 chars

- filter/etc/e-smith/templates/etc/rspamd/local.d/external_services.conf/10base
The extended mode can create some false positive, we need to disable it
https://github.com/NethServer/dev/issues/6334
> Disable oletools extended mode

- nethserver-mail.spec
Do not fail if nethserver-httpd-admin is not installed
NethServer/dev#6320
> filter: add /etc/httpd/admin-conf.d dir

- nethserver-mail.spec
> spec common: require nethserver-httpd-admin-service

- api/imapsync/read
- imapsync/usr/lib/systemd/system/imapsync@.service
Avoid to sync and count shared folders messages
Refer to https://github.com/NethServer/dev/issues/6373
> imapsync. avoid to sync shared folders

- .travis.yml
Authenticate with Docker to avoid pull rate limits.
> Fix Travis build for Docker limits

- ui/src/views/Imapsync.vue
Fixed ImapSync typo errors.
NethServer/dev#6376
> ui. fix imapsync typo errors

- filter/etc/e-smith/templates/etc/rspamd/rspamd.conf/01TrustedNetwork
- filter/etc/e-smith/templates/etc/rspamd/rspamd.conf/20Options
> fix syntax of local_addrs

- api/send/validate
- smarthost/etc/e-smith/templates/etc/postfix/sasl_passwd/30smarthost_password_recipient
- smarthost/etc/e-smith/templates/etc/postfix/tls_policy/10smarthost-policy
See individual commit messages for details
https://github.com/NethServer/dev/issues/6495
See also the [usage of SmartHostName prop](https://github.com/NethServer/nethserver-mail/search?q=org%3Anethserver+SmartHostName), the [fix for the system-wide validator](https://github.com/NethServer/nethserver-cockpit/pull/334)
> Implement new relay sender validation

- filter/etc/e-smith/db/configuration/defaults/clamd@rspamd/status
- filter/etc/e-smith/db/configuration/defaults/clamd@rspamd/type
https://github.com/NethServer/dev/issues/6647
> Stop clamd@rspamd when filter is removed
